name: Run shortlist (dev)

on:
  repository_dispatch:
    types: [dev-deployed] 
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }} 
      - name: Download test files
        run: aws s3 cp s3://permanent-repos/test_files/critical-path.zip .
      - name: Unarchive test files
        run: unzip critical-path.zip
      - name: Run the test
        run: python -m permanent_upload dev files/
