name: Run shortlist (staging)

on:
  repository_dispatch:
    types: [staging_deployed]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Download test files
        run: aws s3 cp s3://permanent-repos/test_files/critical-path.zip .
      - name: Unarchive test files
        run: unzip critical-path.zip
      - name: Run the test
        run: python -m permanent_upload staging files/
  notify:
    runs-on: ubuntu-latest
    if: always()
    needs: execute
    steps:
      - name: Post a message in slack
        run: curl -X POST -H 'Content-type:application/json' --data '{"text":"${{ needs.execute.result }} on staging"}' https://hooks.slack.com/services/TBBFM3TEY/B02HZB4Q8EN/${{ secrets.SLACK_TOKEN }}
